name: rodsiagarage
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  bloc: ^7.1.0
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  getwidget: ^2.0.4
  shimmer: ^2.0.0
  top_snackbar_flutter: ^1.0.0
  flushbar: ^1.10.4
  toast: ^0.1.5
  rxdart: ^0.27.1
  logging: ^1.0.1
  lite_rolling_switch: ^0.1.1
  flutter_switch: ^0.3.2
  flutter_native_splash: ^1.2.1
  fswitch: ^1.1.2
  flutter_form_builder: ^6.1.0+1
  logger: ^1.1.0

  google_maps_flutter: ^2.0.8
  geolocator: ^7.0.3
  geocoding: ^2.0.1
  slider_button: ^1.0.0
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.0.0
  dot_pagination_swiper: ^0.1.1
  cached_network_image: ^3.1.0
  form_field_validator: ^1.1.0
  flutter_multi_formatter: ^2.3.8
  sms_autofill: ^2.0.0
  sms_otp_auto_verify: ^1.2.2
  flutter_slidable: ^0.6.0
  direct_select: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.1
  json_serializable: ^4.1.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon-notify.png
    - assets/images/icon-profile.png
    - assets/images/icon-profile2.png
    - assets/images/icon-profile-homePage.png
    - assets/images/icon-inbox.png
    - assets/images/icon-home.png
    - assets/images/icon-battery.png
    - assets/images/icon-car.png
    - assets/images/icon-distance.png
    - assets/images/icon-location2.png
    - assets/images/icon-desc.png
    - assets/images/icon-call.png
    - assets/images/icon-message.png
    - assets/images/icon-moreOption.png
    - assets/images/icon-history.png
    - assets/images/icon-serviceOfGarage.png
    - assets/images/icon-supportCenter.png
    - assets/launcher/ic_launcher.png
    - assets/images/icon-location-requestCard.png
    - assets/images/icon-break.png
    - assets/images/icon-fuel.png
    - assets/images/icon-engine-oil.png
    - assets/images/icon-rickshaw.png
    - assets/images/icon-tire.png
    - assets/images/icon-battery.png
    
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit     
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
